# Site settings
title: Ganesh Iyer | Product Designer, UX
tagline: "Persuasion over persistence"
# url: "https://www.ganeshviswanathan.com" # The base hostname & protocol for your site. Use it if you need absolute URL's
# baseurl: 
# Social
twitter: iyerport
github: ganesh-iyer
behance: iyerport
medium: iyerport
linkedin: ganeshiyerv
angel: ganeshiyerv
berkeley: ganesh.v
university: ganesh-viswanathan-iyer

# Contact
email: "ganesh.v@berkeley.edu" # This is my real email address. Please don't email me.

# Use this for production
sass:
   sass_dir: _sass
   style: compressed

exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]
